mode = "rigctld"

[rigctl]
rigctl_path = "/usr/bin/rigctl"
model_id = 3085
device = "/dev/ttyACM0"

[rigctld]
address = "127.0.0.1:4532"

[commands]
open = []
close = []
tx = [
  "L", "MONITOR_GAIN", "0.15",
  "M", "PKTLSB", "-1",
  "T", "1",
]
rx = [
  "T", "0",
  "M", "LSB", "-1",
  "L", "MONITOR_GAIN", "0.0",
]
